#!/usr/bin/env bash
# script that transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no UserKnownHostsFile=/dev/null "$1" "$3"@"$2":~/ -i "$4"
  # StrictHostKeyChecking=no
fi

# scp resources.md ubuntu@18.234.105.144:~/
