#!/usr/bin/env bash
# install nginx web server on the server

# updated server
sudo -y apt-get update

# install ngnix web server
sudo apt-get install ngnix

# listen to port 80
nc -l -p 80

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
