#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

# install nginx web server on the server

# updated server
sudo apt-get -y update

# install ngnix web server
sudo apt-get -y install ngnix

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sed -i "40i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# Test the Nginx configuration for syntax errors
sudo service nginx reload
