#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get -y install ngnix
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $string" /etc/nginx/sites-available/default
sudo service nginx restart
