#!/usr/bin/env bash
# custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get update

sudo apt-get -y install nginx

sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/page_404.html

sudo sed -i "28i \\\terror_page 404 \/page_404.html;\n\tlocation = \/page_404.html {\n\t\troot \/var\/www\/html; \n\t\tinternal;\n\t}" /etc/nginx/sites-available/default

sudo service nginx restart
