#!/usr/bin/env bash
# custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404_error.html
string="\\\terror_page 404 \/404_error.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "28i $string" /etc/nginx/sites-available/default
sudo service nginx restart
