#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains the name of the custom HTTP

sudo sed -i "/server_name _;/a\\\tadd_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default

# restart after configuration
sudo service nginx restart
