#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo echo "frontend my-website
        bind *:80
        default_backend all_servers

backend all_servers
        balance roundrobin
        server 316762-web-01 18.234.105.144:80 check
        server 316762-web-02  54.165.39.106:80 check

" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
