#!/usr/bin/env bash
# script that displays a list of currently running processes.
# Must show all processes, for all users, including those which
# might not have a TTY
# Display in a user-oriented format and Show process hierarchy
# list="$(ps aux)"
# echo "$list"

ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command
pstree
