#!/usr/bin/env bash
# Process and PID file


# create file myscript.pid
sudo touch /var/run/myscript.pid
sudo chmod 1777 /var/run/myscript.pid

# save script's PID to the file myscript.pid
echo $$ > /var/run/myscript.pid

sighHandlerTerm()
{
	echo "I hate the kill command"
	sudo rm -f /var/run/myscript.pid
	exit 1
}
sighHandlerInt()
{
	echo "Y U no love me?!"
	exit
}

trap sighHandlerTerm SIGTERM
trap sighHandlerInt SIGINT

while true; do

	echo "To infinity and beyond"
	sleep 2
done
