#!/usr/bin/env bash
# script that displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

a=1

while [ $a -le 100 ]
do
    if ((a % 15 == 0))
    then
	echo "FizzBuz"
    elif  ((a % 3 == 0))
    then
    	echo "Fizz"
    elif ((a % 5 == 0))
    then
    	echo "Buzz"
    else
    	echo "$a"
    fi
    ((a++))
done
