#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

i=0

while [ $i -le 12 ]
do
	echo "Hour: $i"
	a=1
	while [ $a -le 59 ]
	do
		echo "$a"
		((a++))
	done
	((i++))
done
