#!/usr/bin/env bash
# script that displays:
# The content of the current directory
# In a list format

for item in *; do
	if [ -f "$item" ] && [[ "$item" != .* ]] && [[ "$item" == *-* ]]; then
		part="${item#*-}"
		echo "$part"
	fi
done
