#!/usr/bin/env bash
# script that gives you information about the school file:


file="school"

# check if the file exists

if [ -e $file ]; then
	echo "school file exists"

	# if the file is empty
	# if the file has a size greater than zero

	if [ -s "$file" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	# if the file is a regular file

	if [ -f $file ]; then
		echo "school is a regular file"
	else
		:
	fi
else
	echo "school file does not exist"
fi


exit $?
