#!/usr/bin/env bash
# configure ubuntu server

cp /etc/hosts /etc/hosts.old
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts.old
sed -i '2i8.8.8.8 facebook.com' /etc/hosts.old
cp -f /etc/hosts.old /etc/hosts
