#!/usr/bin/env bash
# configure ubuntu server
sudo cp /etc/hosts /etc/hosts.old

sudo sed -i 's/127.0.0.1	localhost/127.0.0.2		localhost/g'
/etc/hosts
sudo sed -i '1a 8.8.8.8		facebook.com' /etc/hosts
