#!/usr/bin/env bash
# script that listens on port 98 on localhost.


nc -l -p 98
# -l: Listen mode, used to create a server that listens for incoming connections.
# -p: Specifies the source port number.
