#!/usr/bin/env bash
# you will need to get Apache to run on the container and to return a
# page containing Hello Holberton when querying the root of it.
# using Docker
# docker exec -ti fb89084725eb /bin/bash
sudo apt-get -y update
sudo apt -y install apache2
sudo service apache2 start
