#!/usr/bin/env bash
# you will need to get Apache to run on the container and to return a
# page containing Hello Holberton when querying the root of it.
# using Docker
sudo docker exec -ti fb89084725eb /bin/bash
sudo apt get update
sudo apt install -y apache2
sudo service apache2 start
