#!/usr/bin/env bash
# scrip Fix this container so that Nginx is running as the nginx user.
sudo pkill -9 apache2 
chown nginx:nginx  /etc/nginx/nginx.conf
chmod 600 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
